# Generated by Django 3.0.6 on 2020-06-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="key", name="major",),
        migrations.AddField(
            model_name="key",
            name="type",
            field=models.CharField(default="maj", max_length=3),
        ),
    ]
