# Generated by Django 3.0.6 on 2020-06-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theory", "0002_auto_20200603_0237"),
    ]

    operations = [
        migrations.AddField(
            model_name="key",
            name="s_f",
            field=models.CharField(
                choices=[("sharp", "♯"), ("flat", "b")],
                default=" ", max_length=5
            ),
        ),
    ]
