# Generated by Django 3.0.6 on 2020-06-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0003_key_s_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='component_pitches',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='key',
            name='s_f',
            field=models.CharField(choices=[('sharp', '♯'), ('flat', 'b')], default='', max_length=5),
        ),
    ]
