# Generated by Django 3.0.6 on 2020-06-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theory", "0004_auto_20200603_2115"),
    ]

    operations = [
        migrations.AddField(
            model_name="key",
            name="component_pitches1",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="key",
            name="component_pitches2",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
