# Generated by Django 3.0.6 on 2020-06-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0005_auto_20200604_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='common',
            field=models.BooleanField(default=False),
        ),
    ]
